### PR TITLE
Extend substrate pallets for parachain runtimes

### LINKED ISSUE #159: Democracy Link disappeared
**Describe the bug**
When opening polkadot.js app on our dev chain the democracy link in the governance tab is not there but should be available to apply for council or submit proposals.

**To Reproduce**
1. Go to https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fnode.dev.sub.zero.io#/explorer
2. Click on Governance Tab
3. See Democracy link is missing
4. click on council
5. See no application possible

**Expected behavior**
The out of the box features should be available.
The Democracy Tab should be available with all its features.

**Screenshots**
image

**Additional context**
We need to use voting on network level internally to get familiar with the process. Therefore we also need the democracy link in the dev chain. 
ℹ️ It was not possible to connect with the rococo parachain to check if its lost there too.

### PR DESCRIPTION
**Pull request by vayesy**
Added next pallets to both `zero` and `subzero` chains:
- democracy
- multisig
- proxy
- membership
- tips
- elections phragmen
- additional pallet dependencies for above.

### CODE REVIEW

**Review by 2075 — COMMENTED** [review]
seems like it is still incomplete / dysfunctional.
also collator nomination seems to be missing.

**Comment by 2075** [comment]
grafik

grafik

grafik

nominate or delegate?

articles
[1] https://substrate.stackexchange.com/questions/2944/pallets-needed-for-staking
[2] https://meta5.world/posts/parachain-staking

**Comment by vayesy** [comment]
@2075 could you extend your answer why do you think it's incomplete / dysfunctional?

As for collator nomination - this wasn't mentioned in the scope of current task. But here are my thoughts on this: at the moment our chain has no collator rewards for proposed blocks. Taking this into account, there are no incentives for other members to participate in collation process. We might think of ways to implement it, but there is no general way to go at the moment. Default rewards implementation (minting reward tokens and distributing them to collators) would introduce inflation for our network, meaning amount of existing tokens increase over time and cost for a single token decreases over time. So this is separate task and discussion, which shouldn't take place here.

**Comment by 2075** [comment]
> @2075 could you extend your answer why do you think it's incomplete / dysfunctional?
> 
> As for collator nomination - this wasn't mentioned in the scope of current task. But here are my thoughts on this: at the moment our chain has no collator rewards for proposed blocks. Taking this into account, there are no incentives for other members to participate in collation process. We might think of ways to implement it, but there is no general way to go at the moment. Default rewards implementation (minting reward tokens and distributing them to collators) would introduce inflation for our network, meaning amount of existing tokens increase over time and cost for a single token decreases over time. So this is separate task and discussion, which shouldn't take place here.

yes, this is not part of a ticket, coming from the initial thesis:

- alphaville was a npos prototype incentivising validator operators to contribute to building a decentralised network. for me the way to go, also according to our product thesis.
- subzero as a parachain lacks incentive for people to operate at the moment.
- the way it is built now assumes a permissioned consortium style network, which is not where we are heading at or from my point of view could but should not head to.
- as a result we should incentivise people to
  - operate collators
  - get rewards for that
  - have a determined amount of collators which can be nominated / delegated
  - from all collators a subset are selected e.g. random to be in the collator set
  - therefore incentive is there to run a collator and through nomination/delegation/selection enough incentive is there to support as a community and get commercial rewards

what alternatives do you have in mind?

**Comment by vovacha** [comment]
> seems like it is still incomplete / dysfunctional.
> regarding incomplete: see first screenshot

@2075 
The idea of this PR is to add three pallets: democracy, multisig, and proxy.
In the first screenshot, there is a council and nothing about mentioned pallets. What did you mean?

**Comment by 2075** [comment]
the first screenshot shows the existence of the council pallet but no option to join

**Comment by vayesy** [comment]
Users shouldn't have direct access to join councils on their behalf.
They can introduce their candidacy and result will be decided by voting outcome.
- https://wiki.polkadot.network/docs/maintain-guides-how-to-join-council

**Comment by 2075** [comment]
yes, can you show an example to achieve this on the current parachain?

**Comment by vayesy** [comment]
Thanks, I'll check it out.

**Comment by vayesy** [comment]
Additionally extended pallets with `membership`, `tips`, `elections`.

**Review by vovacha — APPROVED** [review]
LGTM. Let's add testing scenario for each PR since we have no CI/CD yet. Something like: `build --release ok, build --benchmarks ok, make test ok`.

**Review by FiberMan — APPROVED** [review]

**Comment by 5-mark** [comment]
@vayesy seems like this PR doesnt run through (failing after 16s).
Can you fix it?

**Comment by vayesy** [comment]
@5-mark this is part of old CI/CD logic (I believe it is cloned with all the source code from other repository). It's not relevant and actually should be removed, so this shouldn't be taken into account at the moment.

**Comment by 2075** [comment]
@vayesy pls look into the conflicts

**Review by 2075 — APPROVED** [review]
lgtm

**Pull request merged**
